#!Questo file serve solo per avviare tutti i servizi contemporaneamente.
services:
  mongo:
    container_name: mongo
    image: docker.io/mongo:8.0.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/etc/mongo:rw
    networks:
      - app-network
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3000:3000
    networks:
      - app-network
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 5173:5173
    networks:
      - app-network
  agente:
    container_name: agente
    build: ./agente
    networks:
      - app-network
  mongo-express:
    container_name: mongo_express
    image: docker.io/mongo-express:1.0.2-20-alpine3.19
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    profiles:
      - dev
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge