#!Questo file serve solo per avviare tutti i servizi contemporaneamente (dev).
services:
  mongo:
    image: docker.io/mongo:8.0.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/etc/mongo:rw

  mongo-express:
    image: docker.io/mongo-express:1.0.2-20-alpine3.19
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  
  backend:
    image: mvp-backend
    build: ./backend
    ports:
      - "3000:3000"

  frontend:
    image: mvp-frontend
    build: ./frontend
    ports:
      - "8080:80"

  agente:
    image: mvp-agente
    build: ./agente

volumes:
  mongo-data: