name: Unit Tests

on:
    pull_request:
        types: [opened, reopened, synchronize]
    push:
      branches:
        - main
        - dev

env:
  CI: y

jobs:
    Backend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node 22
              uses: actions/setup-node@v4
              with:
                node-version: 22.x
                cache: 'npm'
                cache-dependency-path: backend/package-lock.json
            - name: Installazione dipendenze
              run: npm ci --prefix ./backend
            - name: Unit testing
              run: npm run test:cov --prefix ./backend

    Frontend:
       runs-on: ubuntu-latest
       steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node 22
              uses: actions/setup-node@v4
              with:
                node-version: 22.x
                cache: 'npm'
                cache-dependency-path: frontend/package-lock.json
            - name: Installazione dipendenze
              run: npm ci --prefix ./frontend
            - name: Unit testing
              run: npm run coverage --prefix ./frontend
        
    Agente:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Setup Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.13'
              cache: 'pip'
          - name: Installazione dipendenze
            run: pip install -r ./agente/requirements.txt
          - name: Unit testing
            run: coverage run -m pytest ./agente && coverage report
