name: Unit Tests

on:
    pull_request:
        types: [opened, reopened, synchronize]
    push:
      branches:
        - main

jobs:
    Backend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                path: './backend'
            #- name: Upload artifacts
            #  uses: actions/upload-artifact@v4
            #  with:
            #    path: ./
            - name: Cd backend
              run: cd backend
            - name: ls
              run: ls -lag
            #- name: Setup Node 22
            #  uses: actions/setup-node@v4
            #  with:
            #    node-version: 22
            #- name: Installazione dipendenze
            #  run: npm ci
            #- name: Unit testing
            #  run: npm test
    #Frontend:
    #   runs-on: ubuntu-latest
        
    #Worker:
    #    runs-on: ubuntu-latest
